# Use the official Node.js image
FROM debian:stable-slim

ARG NODE_VERSION=22

# Replace with your desired Node.js version
RUN apt-get update && \
    apt-get install -y curl gnupg && \
    mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_VERSION.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list && \
    apt-get update && \
    apt-get install -y nodejs

        # Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json .

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Binaries scripts
RUN groupadd --gid 10001 webuser && \
    useradd --gid 10001 --uid 10001 --home-dir /app webuser

RUN chown -R webuser:webuser /app && \
    chmod -R 755 /app

# Expose the application port
EXPOSE 3000

USER webuser

# Start the application using Vite's development server
CMD ["npm", "run", "dev"]